apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---


apiVersion: elasticweb.example.com/v1
kind: ElasticWeb
metadata:
  namespace: dev
  name: elasticweb-sample
spec:
  # TODO(user): Add fields here
  # Add fields here
  image: tomcat:8.0.18-jre8
  nodePort: 30004
  port: 8080
  targetPort: 8080
  podPort: 8080
  singlePodQPS: 500
  totalQPS: 600
  resources:
    limits:
      cpu: 400m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  protocol: TCP
