apiVersion: elasticweb.example.com/v1
kind: ElasticWeb
metadata:
  name: elasticweb-sample
spec:
  # TODO(user): Add fields here
  # Add fields here
  name: http
  nodePort: 30004
  port: 8081
  podPort: 8080
  image: dockerhubyu/expose-prometheus-demo:0.0.1-SNAPSHOT
  targetPort: 8080
  mtargetPort: 8090
  singlePodQPS: 50
  totalQPS: 10
  resources:
    limits:
      cpu: 800m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  protocol: TCP
